#!/usr/bin/expect

eval spawn ssh -oStrictHostKeyChecking=no -oCheckHostIP=no hguser@192.168.61.1

set timeout 3
set prompt *root@OpenWrt*
# Send first password
expect "*assword:"
send "Hp@9wYs2d%t7\r"

expect "*hguser@OpenWrt*"
send "su root\r"

expect "*assword:"
send "865abe62b793\r"

expect $prompt
send "\./container/packages/trcli stop testapp\r"

expect $prompt
send "\./container/packages/trcli uninstall testapp\r"

set APPURL http://192.168.61.171:8000/testapp-1.0.tar.gz

expect $prompt
send "\./container/packages/trcli install $APPURL testapp\r"

sleep 5

expect $prompt
send "\./container/packages/trcli start testapp\r"

sleep 5
expect $prompt
send "lxc-ls -f\r"

expect $prompt
